# Default configuration for Human-AI Interaction Framework

# Framework configuration
framework:
  # Human responsibilities
  human_responsibilities:
    - "Define vision, strategic objectives, and contextual expertise"
    - "Provide clear instructions, ongoing feedback, and ethical oversight"
    - "Make final decisions based on comprehensive information"

  # AI responsibilities
  ai_responsibilities:
    - "Generate data-driven insights, technical solutions, and creative recommendations"
    - "Adhere to ethical guidelines and respond to instructions with precision"
    - "Engage in iterative improvements and document reasoning behind suggestions"

  # Ethical principles to use
  ethical_principles:
    - "TRANSPARENCY"
    - "ACCOUNTABILITY"
    - "PRIVACY"
    - "FAIRNESS"

  # Communication protocols to use
  communication_protocols:
    - "STRUCTURED_DIALOGUE"
    - "CLARIFICATION"
    - "CONSISTENCY"

  # Feedback mechanisms to use
  feedback_mechanisms:
    - "IMMEDIATE"
    - "SCHEDULED"
    - "ISSUE_TRACKING"

  # Improvement processes to use
  improvement_processes:
    - "CONTINUOUS_LEARNING"
    - "RETROSPECTIVE_ANALYSIS"
    - "INCREMENTAL_ENHANCEMENT"

  # Collaboration workflows to use
  collaboration_workflows:
    - "TASK_DISTRIBUTION"
    - "COMMUNICATION_CHANNELS"
    - "DOCUMENTATION"

# Logging configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  log_to_file: false
  log_file: "logs/human_ai_framework.log"

# Application configuration
application:
  name: "Human-AI Interaction Framework"
  version: "0.1.0"
  description: "A robust, ethical, and transparent collaborative framework between human users and AI systems for digital product design and development."
